# Generated by Django 4.2.16 on 2024-11-26 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProductos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionDeFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=False)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='sesionfotografica',
            name='activo',
            field=models.BooleanField(default=False),
        ),
    ]
